executor: slurm
slurm:
  command: "sbatch"
  submit-template: >-
    --partition={resources.partition}
    --cpus-per-task={resources.cpus_per_task}
    --mem={resources.mem}
    --time={resources.runtime}
    --job-name=smk_{rule}
    --account=yuk5
    --output=logs/slurm/{rule}.%j.out
    --error=logs/slurm/{rule}.%j.err
default-resources:
  - slurm_partition=defq
  - mem=8gb
  - runtime=172800
  - extra=""
jobs: 100
latency-wait: 60
local-cores: 8
restart-times: 1
max-jobs-per-second: 2
keep-going: True
rerun-incomplete: True
rerun-triggers: mtime
printshellcmds: True
scheduler: greedy
use-conda: False
conda-frontend: mamba
max-status-checks-per-second: 1
local-cores: 8
