samplesheet:
    samplesheet.tsv

workdir:
    /path/to/workdir

bindpath:
    /mnt/nfs,/home/kaiyu,/Labs,/Projects

intervals: 50

conda:
    align: align

partition:
    normal: defq
    highmem: defq
account:
    yuk5

